export const AstrologersData = [
  {
    name: 'Deepak',
    image: './images/astrologer1.png',
    rating: 4.5,
    specializations: ['Vedic', 'Numerology', 'Prashna'],
    languages: ['Hindi', 'English', 'Gujarati'],
    experience: 10,
    originalPrice: 25,
    discountedPrice: null,
    isBusy: false,
    isFree: true,
    waitTime: 0,
    isVerified:true,
  },
  {
    name: 'Pushpak',
    image: './images/astrologer2.png',
    rating: 4.5,
    specializations: ['Vedic', 'Numerology', 'Prashna'],
    languages: ['Hindi', 'English', 'Gujarati'],
    experience: 10,
    originalPrice: 25,
    discountedPrice: 5,
    isBusy: false,
    isFree: true,
    waitTime: 0,
    isVerified:true,
  },
  {
    name: 'Tripti',
    image: './images/astrologer3.png',
    rating: 4.5,
    specializations: ['Vedic', 'Numerology', 'Prashna'],
    languages: ['Hindi', 'English', 'Gujarati'],
    experience: 10,
    originalPrice: 25,
    discountedPrice: 5,
    isBusy: false,
    isFree: false,
    waitTime: 0,
    isVerified:true,
  },
  {
    name: 'Aarohi',
    image: './images/astrologer4.png',
    rating: 4.5,
    specializations: ['Vedic', 'Numerology'],
    languages: ['Hindi', 'English', 'Gujarati'],
    experience: 10,
    originalPrice: 25,
    discountedPrice: null,
    isBusy: false,
    isFree: false,
    waitTime: 0,
    isVerified:true,
  },
  {
    name: 'Mahima',
    image: './images/astrologer5.png',
    rating: 4.5,
    specializations: ['Vedic', 'Numerology', 'Prashna'],
    languages: ['Hindi', 'English', 'Gujarati'],
    experience: 10,
    originalPrice: 25,
    discountedPrice: null,
    isBusy: true,
    isFree: false,
    waitTime: 7,
    isVerified:true,
  },
  {
    name: 'Khushboo',
    image: './images/astrologer6.png',
    rating: 4.5,
    specializations: ['Vedic', 'Numerology', 'Prashna'],
    languages: ['Hindi', 'English', 'Gujarati'],
    experience: 10,
    originalPrice: 25,
    discountedPrice: null,
    isBusy: true,
    isFree: false,
    waitTime: 7,
    isVerified:true,
  },
  {
    name: 'Aarohi',
    image: './images/astrologer4.png',
    rating: 4.5,
    specializations: ['Vedic', 'Numerology'],
    languages: ['Hindi', 'English', 'Gujarati'],
    experience: 10,
    originalPrice: 25,
    discountedPrice: null,
    isBusy: false,
    isFree: false,
    waitTime: 0,
    isVerified:true,
  },
  {
    name: 'Mahima',
    image: './images/astrologer5.png',
    rating: 4.5,
    specializations: ['Vedic', 'Numerology', 'Prashna'],
    languages: ['Hindi', 'English', 'Gujarati'],
    experience: 10,
    originalPrice: 25,
    discountedPrice: null,
    isBusy: true,
    isFree: false,
    waitTime: 7,
    isVerified:true,
  },
  {
    name: 'Khushboo',
    image: './images/astrologer6.png',
    rating: 4.5,
    specializations: ['Vedic', 'Numerology', 'Prashna'],
    languages: ['Hindi', 'English', 'Gujarati'],
    experience: 10,
    originalPrice: 25,
    discountedPrice: null,
    isBusy: true,
    isFree: false,
    waitTime: 7,
    isVerified:true,
  },
  // Add more astrologers similarly...
];
